name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{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}}
        issue-message: "Hello! This is your first issue! Make sure to read the rules"
        pr-message: "Hi dev! Thanks for helping us! This is your first pull."
